# Generated by Django 2.1.1 on 2018-09-29 09:03

from django.db import migrations, models

"""
    Add field to directionmodel
"""
class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionmodel',
            name='sequence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
