# Generated by Django 2.1.1 on 2018-09-30 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_directionmodel_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='r_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
