# Generated by Django 2.1.1 on 2018-10-24 14:20

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0003_auto_20180930_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='directionmodel',
            name='detail',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='directionmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='directions', to='food.RecipeModel'),
        ),
        migrations.AlterField(
            model_name='directionmodel',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='detail',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='categories',
            field=models.ManyToManyField(to='food.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加的时间'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='desc',
            field=models.CharField(blank=True,max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(to='food.IngredientModel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='r_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
