# Generated by Django 2.1.1 on 2018-10-08 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20181008_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_answered', to='invitation.AnswerModel'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_answered', to='invitation.MessageModel'),
        ),
    ]
