# Generated by Django 2.1.1 on 2018-09-30 01:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Create an item to store in the bag.
    Create a bag for the newly created user.
    """
    dependencies = [
        ('food', '0003_auto_20180930_0147'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('inputted_time', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.IngredientModel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='bagitemmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
