# Generated by Django 2.1.1 on 2018-10-08 08:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Define operation of:
    updating item expiration date
    updating item in bage
    updating bag entry date
    updating user associated with the bag 
    updating quantities of item in bag
    """


    dependencies = [
        ('user', '0003_auto_20181003_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitemmodel',
            name='expire_time',
            field=models.DateTimeField(blank=True, help_text='update item expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='bagitemmodel',
            name='ingredients',
            field=models.ForeignKey(help_text='item', on_delete=django.db.models.deletion.CASCADE, to='food.IngredientModel'),
        ),
        migrations.AlterField(
            model_name='bagitemmodel',
            name='inputted_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='item bag entry date'),
        ),
        migrations.AlterField(
            model_name='bagitemmodel',
            name='user',
            field=models.ForeignKey(help_text='user associated with the bag', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bagitemmodel',
            name='weight',
            field=models.FloatField(help_text='quantity'),
        ),
    ]
