# Generated by Django 2.1.1 on 2018-10-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Alter ingredients field in the bag
    """
    dependencies = [
        ('user', '0004_auto_20181008_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitemmodel',
            name='ingredients',
            field=models.ForeignKey(help_text='item', on_delete=django.db.models.deletion.CASCADE,
                                    to='food.CategoryModel'),
        ),
    ]
