# Generated by Django 2.1.1 on 2018-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    upate item input date
    """
    dependencies = [
        ('user', '0007_auto_20181101_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitemmodel',
            name='inputted_time',
            field=models.DateField(auto_now=True, help_text='item input date'),
        ),
    ]
